server:
  port: 8080   # Inside container, you map it to 8081 in docker-compose

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/trading_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: oms
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: kafka:9092   # ✅ service name in docker-compose network
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        linger.ms: 5
        max.in.flight.requests.per.connection: 5
    consumer:
      group-id: oms
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

app:
  topicPrefix: ${TOPIC_PREFIX:tp}
  oms:
    ioc-timeout-ms: 2000
    day-end-cron: "0 0 10 * * *"
  market:
    openIst: "09:15"
    closeIst: "15:30"
    holidays: ["2025-01-26","2025-08-15"]