CREATE TABLE IF NOT EXISTS holidays (
  id SERIAL PRIMARY KEY,
  date DATE UNIQUE NOT NULL,
  source VARCHAR(32) NOT NULL DEFAULT 'manual',
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
