name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Release version (e.g., 0.1.0)"
jobs:
  docker_and_helm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build artifacts
        run: ./mvnw -q -DskipTests clean package

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push images
        run: |
          TAG=${{ github.event.inputs.version }}
          for svc in oms risk portfolio marketdata exec-adapter outbox-dispatcher; do
            docker build -t ghcr.io/${{ github.repository }}-$svc:$TAG ./services/$svc
            docker push ghcr.io/${{ github.repository }}-$svc:$TAG
          done

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package charts
        run: |
          mkdir -p dist
          for c in oms risk portfolio marketdata exec-adapter outbox-dispatcher; do
            helm package ops/k8s/$c -d dist/
          done

      - name: Publish charts to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
